### ISSUE TITLE
Big Shoulders Instance Names

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/big_shoulders#4]
The update process of Big Shoulders will include two sibling families (Stencil and Inline) with a Variable font for each of the three. The idea is to do it in a chain of [releasing steps](https://github.com/google/fonts/issues/2426#issuecomment-629001524) to ease the transition between current TTFs, named "Text" and "Display", to the new statics fonts of the Variable.

I've been working on Big Shoulders (standard variant) as a pilot to solve any possible issues on it, and then replicate the process for the new families. The statics fonts are "technically" ready to be published (after solving vertical metrics, kerning, regression, among others). 

The variable font has now only 1 FAIL (regarding [not include the opsz axis](https://github.com/vv-monsalve/big_shoulders/issues/3)), however when I tested it on Samsa, the Instances names have the weight name, but they don't include the reference "Text" or "Display" related to the opsz.

<img width="1242" alt="Screen Shot 2020-06-18 at 01 41 47" src="https://user-images.githubusercontent.com/48698976/84986924-f6fd4380-b104-11ea-9268-970aec59f83e.png">
----

Before having this instance name Issue, I performed two changes to fix previous FB Fails.

1.  The opsz particles were included as part of a familyName custom parameter on each instance to match the current name schema, e.g., BigShouldersText-Regular.ttf, as well as to solve two [previous Fails](https://github.com/vv-monsalve/big_shoulders/issues/2) on the static fonts. 

<img width="873" alt="Screen Shot 2020-06-18 at 01 43 27" src="https://user-images.githubusercontent.com/48698976/84987060-2ca22c80-b105-11ea-9d89-134da1bff240.png">

2. That custom parameter led at that moment to a[ Fail on Typographic Subfamily Name for win](https://github.com/vv-monsalve/big_shoulders/issues/3#issuecomment-645825630) on the Vf. So, to avoid any conflict, as the "Text" reference would no longer be needed on the variable font, I removed it from the name tables using a [fixName.py](https://github.com/vv-monsalve/big_shoulders/blob/QA-BigShoulders/source/fixName.py) file. Anyhow, I think this wouldn't be the cause of the instance name issue since I inspected a Vf done before to this change, and it was already present on that font.

----

What could be the best practice to solve this Instance name on the Vf?. Maybe, probably, this is a silly thing, and I'm missing something, but I've tried many things with no positive outcomes.

I even returned to include those particles back on the Style Name. Nevertheless, while this solves the instance name issue on the Variable font, it would also return to the previous fails on the statics and the names would end up like BigShoulders-TextRegular.ttf which wouldn't match the names of the published font, that is a requisite of the update.

Current last files are in the[ QA-BigShoulders Branch](https://github.com/vv-monsalve/big_shoulders/tree/QA-BigShoulders)

**Comment by m4rc1e** [comment]
Apologies for the delay in this reply.

Myself and Dave have been discussing what to do regarding fvar instance names and STAT entries for VFs. Atm, I'm currently updating the spec to reflect our discussions.

---


For this project, I think we should do the following:

Release Big Shoulders VF which has the following setup:

**fvar**
Instance names should be Thin to Black. Do not include the opsz particles in the instance names. This means you should only have 9 fvar instances in total.

**STAT**
Use DaMa statmake to generate a STAT table which contains two axis records. One for weight, the other for optical size.

I've used statmake on [Inconsolata](https://github.com/googlefonts/inconsolata) to produce a STAT table that has a similar setup (wdth, wght). It produces the following drop downs in Samsa:

<img width="290" alt="Screenshot 2020-06-19 at 14 21 15" src="https://user-images.githubusercontent.com/7525512/85136935-5019c400-b238-11ea-99eb-4af70eba0146.png">

<img width="295" alt="Screenshot 2020-06-19 at 14 25 47" src="https://user-images.githubusercontent.com/7525512/85137255-cd453900-b238-11ea-877f-bb345a47be6c.png">


_Users can select weights and widths individually_


Once Big Shoulders VF is done, I'd get GF eng to delist both Big Shoulders Text and Big Shoulders Display from the Google Fonts website.

**Comment by vv-monsalve** [comment]
Thanks, Marc for your comments.

> Instance names should be Thin to Black. Do not include the opsz particles in the instance names. This means you should only have 9 fvar instances in total.

Previously we had talked about [keeping them](https://github.com/google/fonts/issues/2426#issuecomment-629001524) on the statics font names to ease the updating process for the users. So I would like to have @davelab6 thoughts on this.

> I've used statmake on Inconsolata to produce a STAT table that has a similar setup (wdth, wght). It produces the following dropdowns in Samsa:

I'll try to create the STAT to see if it helps and check Inconsolata to see the how dropdowns were possible

**Comment by m4rc1e** [comment]
Auch, I forgot all about Dave's post. 

Apologies for the confusion. His plan does seem much better imo and we should follow it.

Personally, if I was doing this project and following Dave's plan, I would do **Step 4** first. I would then use fontTools varLib.instancer and some post processing scripts to produce Steps 2 and 3.

**Comment by vv-monsalve** [comment]
Yes, I agree it would be the 'cleanest' way. I'm working on it, that's why I now have this Issue with the opsz+wght particles in the name.

To summarise the situation, it would be:

If I include the opsz particles "Text" and "Display" on the Style Name, it arises [two FB Fails](https://github.com/vv-monsalve/big_shoulders/issues/2), and the resulting font name `BigShoulders-TextRegular.ttf` wouldn't match the name of the published ones `BigShouldersText-Regular.ttf`, but the instance names on the Variable font are ok.

On the other hand, if I add a fontFamily custom parameter to include the opsz particles in the name of the font, it solves the Fails plus the names match, but the instance names on Variable end up only with weight names and no opsz references for both, Text and Display variants.

I checked on Merriweather as a reference, but currently, they are using opsz+weight particles on the Style Name, so I found the same fails when I ran FB locally to test it.

**Comment by vv-monsalve** [comment]
I think it is solved!

I have now:

- [Static Instances](https://github.com/vv-monsalve/big_shoulders/tree/QA-BigShoulders/fonts/ttf/Big-Shoulders) with matching names `BigShouldersText-Regular.ttf` and 0 FB Fails
- [Variable font (opsz, wght)](https://github.com/vv-monsalve/big_shoulders/blob/QA-BigShoulders/fonts/variable/BigShouldersDisplay%5Bwght%5D.ttf). The Fail about not including an opsz axis still reported though.
- Variable `[wght]` font for each [Text](https://github.com/vv-monsalve/big_shoulders/blob/QA-BigShoulders/fonts/variable/BigShouldersText%5Bwght%5D.ttf) and [Display](https://github.com/vv-monsalve/big_shoulders/blob/QA-BigShoulders/fonts/variable/BigShouldersDisplay%5Bwght%5D.ttf) sibling families. They both report a single Fail regarding the opsz particles Text and Variable included in the name. But I think this Fail could be skipped for this project:

<details>
<summary>🔥 <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/canonical_filename](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/canonical_filename)
<pre>--- Rationale ---

A font&#x27;s filename must be composed in the following manner:
&lt;familyname&gt;-&lt;stylename&gt;.ttf

- Nunito-Regular.ttf,
- Oswald-BoldItalic.ttf

Variable fonts must list the axis tags in alphabetical order in square brackets
and separated by commas:

- Roboto[wdth,wght].ttf
- Familyname-Italic[wght].ttf


</pre>

* 🔥 **FAIL** The file 'BigShouldersDisplay[wght].ttf' must be renamed to 'BigShoulders[wght].ttf' according to the Google Fonts naming policy for variable fonts. [code: bad-varfont-filename]

</details>

**Comment by vv-monsalve** [comment]
This issue is not entirely solved yet. I've been working on it and I'll summarize the main steps done.

### Approach 1

When using the above approach 1 (from the previous comment), the results were:

- 1 Source file
- 0 FB Fails on Files
- Samsa review Ok
- The opsz particle was not included in the style name when displayed on Adobe apps (like Indesign, picture below)

![Screen Shot 2020-06-30 at 11 29 05](https://user-images.githubusercontent.com/48698976/86274654-a02d4a80-bb97-11ea-80ba-b25e2d9bc621.png)




The tricky part for this project has been to keep the name of the currently published fonts, which includes the opsz particle as part of the Font name itself `BigShouldersText-Regular.ttf` and not as a style name `BigShoulders-TextThin.ttf` (as it's used in other projects such as Inconsolata e.g., `Inconsolata-CondensedBlack.ttf`)

The above Approach 1 use a familyName custom parameter to add that particle to the Font name, which led to the mentioned results. 

Trying to solve the Adobe apps issue, from a conversation with Chris he told me he noticed it was regarding the fvar table. So, new custom parameters were added in the Instances on source file (WWSFamilyName, WWSSubfamilyName, Name Table Entry, Name Table Entry), but they didn't solve it either. 

It seems that the fvar table needs to have both particles (opsz and weight) as part of the Style Name to include them rightly.

![Screen Shot 2020-07-01 at 12 43 37](https://user-images.githubusercontent.com/48698976/86275242-922bf980-bb98-11ea-8ea1-934f98ba0b9a.png)

----

### Approach 2

Thus, after that, I followed a different approach where two different files would be needed. I created a new source file to handle only the variable fonts. In it, I added the particle directly on the Style Name and deleted de familyName custom parameter, and the results so far are:

- 2 Source files
- Static fonts generated from a different source file. They have 0 FB Fails and matching names with the currently published version.
- Variable font with [1 FB Fail](https://github.com/vv-monsalve/big_shoulders/blob/2640d5e1d187c0864bf12bf5a54a435276d003b0/fonts/variable/qaBigShoulders-vf-11newsource.md#L219), regarding the Text particle that is included now in name ID 17.
- Variable font displaying ok both in Adobe apps and Samsa.
- Static fonts that perfectly match with its parallel version on the variable font.

![Screen Shot 2020-07-01 at 12 51 07](https://user-images.githubusercontent.com/48698976/86275974-b805ce00-bb99-11ea-96d8-45065f53f733.png)

![Screen Shot 2020-07-01 at 10 54 21](https://user-images.githubusercontent.com/48698976/86275462-f0f17300-bb98-11ea-8252-66b15bea3525.png)

![Screen Shot 2020-07-01 at 12 53 37](https://user-images.githubusercontent.com/48698976/86276108-f0a5a780-bb99-11ea-8b57-2349d90550e3.png)

----

What would be pending now is:

- [ ] To remove the Text particle of the name ID 17, which is causing a Fail. I would have to figure out how to solve it from the fixName.py file, I guess it could be possible. @m4rc1e any hint here to save some time would be appreciated :)

- [ ] Having solved that, to create the intermediate Variable fonts, both for Text and Display variants separately including only the weight axis, using the Instancer tool.

The last question would be: Having opsz and weight particles working well on the big variable font, and once I solve the name ID 17, would we stick to the idea of having partial releases for only weight variable fonts? `BigShouldersText[wght].ttf` and `BigShouldersDisplay[wght].ttf` or could we release the entire variable `BigShoulders[opsz,wght].ttf`?

**Comment by vv-monsalve** [comment]
Sources and files to replicate on [QA-BigShoulders-VF branch](https://github.com/vv-monsalve/big_shoulders/tree/QA-BigSHoulders-VF)

**Comment by m4rc1e** [comment]
I'm going to look into this. Please move onto a different project.

**Comment by m4rc1e** [comment]
See #5. This should output all the fonts we want. I haven't touched the sibling families though,.

**Comment by vv-monsalve** [comment]
Thanks, @m4rc1e for taking the time on this!

I've merged and inspected the files. I now see the use of the design space, the GDEF table, and the way the Instancer command was included directly on the build. Just in case, I did use it to create the partial VFs when I thought this was done, but I didn't add it to the build, which makes more sense.

Nevertheless, when testing the `BigShoulders[opsz,wght].ttf` font in Adobe apps, the menu is showing only the weight on the menu list. 

Indesign
![Screen Shot 2020-07-02 at 11 09 54](https://user-images.githubusercontent.com/48698976/86390593-f369d080-bc5d-11ea-8bc2-c205e70235a2.png)

Illustrator
![Screen Shot 2020-07-02 at 11 54 23](https://user-images.githubusercontent.com/48698976/86390603-fb297500-bc5d-11ea-9c6f-85eb5b7495b8.png)

In this way, the user will only know there is an option for the optical size when displaying the Variable font panel options, which at the same time, are only accessible when clicking on the tiny button on the right side of the Styles submenu.

Particularly given only eight fonts (variables) are announced.

Would it be ok? Would it be the intended way?

![Screen Shot 2020-07-02 at 12 05 14](https://user-images.githubusercontent.com/48698976/86391658-c5858b80-bc5f-11ea-80fb-4047d0ff8aed.png)

![Screen Shot 2020-07-02 at 12 03 45](https://user-images.githubusercontent.com/48698976/86390685-257b3280-bc5e-11ea-9f62-13160f40570e.png)

![Screen Shot 2020-07-02 at 12 19 23](https://user-images.githubusercontent.com/48698976/86390768-4b083c00-bc5e-11ea-82da-3c2a5df3cd19.png)

**Comment by m4rc1e** [comment]
> Nevertheless, when testing the BigShoulders[opsz,wght].ttf font in Adobe apps, the menu is showing only the weight on the menu list.

That's intentional and part of our upcoming spec. The STAT table UI (once Adobe implements it) will allow for selecting opsz and wght particles as well.

**Comment by vv-monsalve** [comment]
Oh! I see… ok. It was worth asking :)
Thanks!

**Comment by vv-monsalve** [comment]
Solved after last Marc's [PR](https://github.com/vv-monsalve/big_shoulders/pull/6)
Closing this here
