### ISSUE TITLE
Big Shoulder Kerning fixes 

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/big_shoulders#8]
After the fixes done on spacing and kerning in BigShoulders there is a reflow on texts.

Visual regressions must be avoided as much as possible according to the spec, but Dave has also said that if the reflow is due to a better kerning, he would pass it. 

So, a revision on this would be needed before making the PR. @m4rc1e and @davelab6, please, have a look at this and let me know your thoughts on this.

Below are some comparative gifs of the fonts

**Big Shoulders Text Regular**

![BigShoulders-Text-Regular](https://user-images.githubusercontent.com/48698976/88396850-b4c0c500-cd88-11ea-972d-620f39be1c48.gif)

**Comment by vv-monsalve** [comment]
**Big Shoulders Text Thin**

![BigShoulders-Text-Thin](https://user-images.githubusercontent.com/48698976/88396999-f05b8f00-cd88-11ea-8b6f-1cce29b10e61.gif)

**Comment by vv-monsalve** [comment]
**Big Shoulders Text Black**

![BigShoulders-Text-Black](https://user-images.githubusercontent.com/48698976/88397081-1123e480-cd89-11ea-97c4-8a177439cc27.gif)

**Comment by m4rc1e** [comment]
> Visual regressions must be avoided as much as possible according to the spec, but Dave has also said that if the reflow is due to a better kerning, he would pass it.

New kerning looks better imo so I don't mind the reflow.

Thanks Viviana.

**Comment by vv-monsalve** [comment]
Ok, good. I'll proceed with the PR process then.
Thanks, @m4rc1e
